class Document:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def render(self, width: int, height: int, scale: float) -> bytes: ...

def load(data: bytes) -> Document | None: ...
def add_font_file(path: str, family: str, bold: bool, italic: bool) -> bool: ...

lunasvg_version: str
